### ISSUE TITLE
Impossible to pull the data through git lfs

### ISSUE THREAD

**Issue by mrkite92** [astrorama/SourceXtractorTutorial#1]
Hi,

On my Mac Pro :

 git lfs install
Updated git hooks.
Git LFS initialized.

git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/astrorama/SourceXtractorTutorial.git/info/lfs'

Thanks for your help,
Cheers,
JB

**Comment by ayllon** [comment]
Try now, I have stored them somewhere else.
You may need a `git pull` to get the new  `.lfsconfig` file.

**Comment by mrkite92** [comment]
Work fine, thanks for immediate fix!

**Comment by ayllon** [comment]
:smile: 
Closing then!
